version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:17-alpine
    container_name: transacciones_postgres
    environment:
      POSTGRES_DB: banco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: JhayderSQL
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - transacciones_network

  # Aplicaci√≥n Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transacciones_app
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/banco
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: JhayderSQL
      SPRING_SQL_INIT_MODE: always
      SPRING_SQL_INIT_PLATFORM: postgres
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - transacciones_network

volumes:
  postgres_data:

networks:
  transacciones_network:
    driver: bridge

